"""
This type stub file was generated by pyright.
"""

import abc
from kafka.vendor import six
from enum import IntEnum

log = ...
NO_PRODUCER_ID = ...
NO_PRODUCER_EPOCH = ...
NO_SEQUENCE = ...
class ProducerIdAndEpoch:
    __slots__ = ...
    def __init__(self, producer_id, epoch) -> None:
        ...
    
    @property
    def is_valid(self) -> bool:
        ...
    
    def match(self, batch):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    
    def __str__(self) -> str:
        ...
    


class TransactionState(IntEnum):
    UNINITIALIZED = ...
    INITIALIZING = ...
    READY = ...
    IN_TRANSACTION = ...
    COMMITTING_TRANSACTION = ...
    ABORTING_TRANSACTION = ...
    ABORTABLE_ERROR = ...
    FATAL_ERROR = ...
    @classmethod
    def is_transition_valid(cls, source, target) -> bool | None:
        ...
    


class Priority(IntEnum):
    FIND_COORDINATOR = ...
    INIT_PRODUCER_ID = ...
    ADD_PARTITIONS_OR_OFFSETS = ...
    END_TXN = ...


class TransactionManager:
    """
    A class which maintains state for transactions. Also keeps the state necessary to ensure idempotent production.
    """
    NO_INFLIGHT_REQUEST_CORRELATION_ID = ...
    ADD_PARTITIONS_RETRY_BACKOFF_MS = ...
    def __init__(self, transactional_id=..., transaction_timeout_ms=..., retry_backoff_ms=..., api_version=..., metadata=...) -> None:
        ...
    
    def initialize_transactions(self) -> TransactionalRequestResult:
        ...
    
    def begin_transaction(self) -> None:
        ...
    
    def begin_commit(self) -> TransactionalRequestResult:
        ...
    
    def begin_abort(self) -> TransactionalRequestResult:
        ...
    
    def send_offsets_to_transaction(self, offsets, consumer_group_id) -> TransactionalRequestResult:
        ...
    
    def maybe_add_partition_to_transaction(self, topic_partition) -> None:
        ...
    
    def is_send_to_partition_allowed(self, tp) -> bool:
        ...
    
    def has_producer_id(self, producer_id=...) -> bool:
        ...
    
    def is_transactional(self) -> bool:
        ...
    
    def has_partitions_to_add(self) -> bool:
        ...
    
    def is_completing(self) -> bool:
        ...
    
    @property
    def last_error(self) -> None:
        ...
    
    def has_error(self) -> bool:
        ...
    
    def is_aborting(self) -> bool:
        ...
    
    def transition_to_abortable_error(self, exc) -> None:
        ...
    
    def transition_to_fatal_error(self, exc) -> None:
        ...
    
    def is_partition_added(self, partition) -> bool:
        ...
    
    def is_partition_pending_add(self, partition) -> bool:
        ...
    
    def has_producer_id_and_epoch(self, producer_id, producer_epoch):
        ...
    
    def set_producer_id_and_epoch(self, producer_id_and_epoch) -> None:
        ...
    
    def reset_producer_id(self) -> None:
        """
        This method is used when the producer needs to reset its internal state because of an irrecoverable exception
        from the broker.

        We need to reset the producer id and associated state when we have sent a batch to the broker, but we either get
        a non-retriable exception or we run out of retries, or the batch expired in the producer queue after it was already
        sent to the broker.

        In all of these cases, we don't know whether batch was actually committed on the broker, and hence whether the
        sequence number was actually updated. If we don't reset the producer state, we risk the chance that all future
        messages will return an OutOfOrderSequenceNumberError.

        Note that we can't reset the producer state for the transactional producer as this would mean bumping the epoch
        for the same producer id. This might involve aborting the ongoing transaction during the initProducerIdRequest,
        and the user would not have any way of knowing this happened. So for the transactional producer,
        it's best to return the produce error to the user and let them abort the transaction and close the producer explicitly.
        """
        ...
    
    def sequence_number(self, tp) -> int:
        ...
    
    def increment_sequence_number(self, tp, increment) -> None:
        ...
    
    def reset_sequence_for_partition(self, tp) -> None:
        ...
    
    def next_request_handler(self, has_incomplete_batches) -> EndTxnHandler | None:
        ...
    
    def retry(self, request) -> None:
        ...
    
    def authentication_failed(self, exc) -> None:
        ...
    
    def coordinator(self, coord_type) -> None:
        ...
    
    def lookup_coordinator_for_request(self, request) -> None:
        ...
    
    def next_in_flight_request_correlation_id(self) -> int:
        ...
    
    def clear_in_flight_transactional_request_correlation_id(self) -> None:
        ...
    
    def has_in_flight_transactional_request(self) -> bool:
        ...
    
    def has_fatal_error(self) -> bool:
        ...
    
    def has_abortable_error(self) -> bool:
        ...
    


class TransactionalRequestResult:
    def __init__(self) -> None:
        ...
    
    def done(self, error=...) -> None:
        ...
    
    def wait(self, timeout_ms=...) -> bool:
        ...
    
    @property
    def is_done(self) -> bool:
        ...
    
    @property
    def succeeded(self) -> bool:
        ...
    
    @property
    def failed(self) -> bool:
        ...
    
    @property
    def exception(self) -> None:
        ...
    


@six.add_metaclass(abc.ABCMeta)
class TxnRequestHandler:
    def __init__(self, transaction_manager, result=...) -> None:
        ...
    
    @property
    def transactional_id(self):
        ...
    
    @property
    def producer_id(self):
        ...
    
    @property
    def producer_epoch(self):
        ...
    
    def fatal_error(self, exc) -> None:
        ...
    
    def abortable_error(self, exc) -> None:
        ...
    
    def fail(self, exc) -> None:
        ...
    
    def reenqueue(self) -> None:
        ...
    
    def on_complete(self, correlation_id, response_or_exc) -> None:
        ...
    
    def needs_coordinator(self) -> bool:
        ...
    
    @property
    def result(self) -> TransactionalRequestResult:
        ...
    
    @property
    def coordinator_type(self) -> Literal['transaction']:
        ...
    
    @property
    def coordinator_key(self):
        ...
    
    def set_retry(self) -> None:
        ...
    
    @property
    def is_retry(self) -> bool:
        ...
    
    @abc.abstractmethod
    def handle_response(self, response) -> None:
        ...
    
    @abc.abstractproperty
    def priority(self) -> None:
        ...
    


class InitProducerIdHandler(TxnRequestHandler):
    def __init__(self, transaction_manager, transaction_timeout_ms) -> None:
        ...
    
    @property
    def priority(self) -> Literal[1]:
        ...
    
    def handle_response(self, response) -> None:
        ...
    


class AddPartitionsToTxnHandler(TxnRequestHandler):
    def __init__(self, transaction_manager, topic_partitions) -> None:
        ...
    
    @property
    def priority(self) -> Literal[2]:
        ...
    
    def handle_response(self, response) -> None:
        ...
    
    def maybe_override_retry_backoff_ms(self) -> None:
        ...
    


class FindCoordinatorHandler(TxnRequestHandler):
    def __init__(self, transaction_manager, coord_type, coord_key) -> None:
        ...
    
    @property
    def priority(self) -> Literal[0]:
        ...
    
    @property
    def coordinator_type(self) -> None:
        ...
    
    @property
    def coordinator_key(self) -> None:
        ...
    
    def handle_response(self, response) -> None:
        ...
    


class EndTxnHandler(TxnRequestHandler):
    def __init__(self, transaction_manager, committed) -> None:
        ...
    
    @property
    def priority(self) -> Literal[3]:
        ...
    
    def handle_response(self, response) -> None:
        ...
    


class AddOffsetsToTxnHandler(TxnRequestHandler):
    def __init__(self, transaction_manager, consumer_group_id, offsets) -> None:
        ...
    
    @property
    def priority(self) -> Literal[2]:
        ...
    
    def handle_response(self, response) -> None:
        ...
    


class TxnOffsetCommitHandler(TxnRequestHandler):
    def __init__(self, transaction_manager, consumer_group_id, offsets, result) -> None:
        ...
    
    @property
    def priority(self) -> Literal[2]:
        ...
    
    @property
    def coordinator_type(self) -> Literal['group']:
        ...
    
    @property
    def coordinator_key(self) -> Any:
        ...
    
    def handle_response(self, response) -> None:
        ...
    


