"""
This type stub file was generated by pyright.
"""

import platform
from kafka.sasl.gssapi import SaslMechanismGSSAPI
from kafka.sasl.msk import SaslMechanismAwsMskIam
from kafka.sasl.oauth import SaslMechanismOAuth
from kafka.sasl.plain import SaslMechanismPlain
from kafka.sasl.scram import SaslMechanismScram
from kafka.sasl.sspi import SaslMechanismSSPI

SASL_MECHANISMS = ...
def register_sasl_mechanism(name, klass, overwrite=...) -> None:
    ...

def get_sasl_mechanism(name):
    ...

if platform.system() == 'Windows':
    ...
else:
    ...
