"""
This type stub file was generated by pyright.
"""

import abc
from kafka.vendor.six import add_metaclass

@add_metaclass(abc.ABCMeta)
class SaslMechanism:
    @abc.abstractmethod
    def __init__(self, **config) -> None:
        ...
    
    @abc.abstractmethod
    def auth_bytes(self) -> None:
        ...
    
    @abc.abstractmethod
    def receive(self, auth_bytes) -> None:
        ...
    
    @abc.abstractmethod
    def is_done(self) -> None:
        ...
    
    @abc.abstractmethod
    def is_authenticated(self) -> None:
        ...
    
    def auth_details(self) -> Literal['Authenticated via SASL']:
        ...
    


