"""
This type stub file was generated by pyright.
"""

from kafka.sasl.abc import SaslMechanism

log = ...
class SaslMechanismAwsMskIam(SaslMechanism):
    def __init__(self, **config) -> None:
        ...
    
    def auth_bytes(self) -> bytes:
        ...
    
    def receive(self, auth_bytes) -> None:
        ...
    
    def is_done(self) -> bool:
        ...
    
    def is_authenticated(self) -> bool:
        ...
    
    def auth_details(self) -> str:
        ...
    


class AwsMskIamClient:
    UNRESERVED_CHARS = ...
    def __init__(self, host, access_key, secret_key, region, token=...) -> None:
        """
        Arguments:
            host (str): The hostname of the broker.
            access_key (str): An AWS_ACCESS_KEY_ID.
            secret_key (str): An AWS_SECRET_ACCESS_KEY.
            region (str): An AWS_REGION.
            token (Optional[str]): An AWS_SESSION_TOKEN if using temporary
                credentials.
        """
        ...
    
    def first_message(self) -> bytes:
        """
        Returns (bytes):
            An encoded JSON authentication payload that can be sent to the
            broker.
        """
        ...
    


