"""
This type stub file was generated by pyright.
"""

from kafka.sasl.abc import SaslMechanism

log = ...
class SaslMechanismPlain(SaslMechanism):
    def __init__(self, **config) -> None:
        ...
    
    def auth_bytes(self) -> bytes:
        ...
    
    def receive(self, auth_bytes) -> None:
        ...
    
    def is_done(self) -> bool:
        ...
    
    def is_authenticated(self) -> bool:
        ...
    
    def auth_details(self):
        ...
    


