"""
This type stub file was generated by pyright.
"""

from kafka.sasl.abc import SaslMechanism
from kafka.vendor import six

log = ...
if six.PY2:
    def xor_bytes(left, right) -> bytearray:
        ...
    
else:
    def xor_bytes(left, right) -> bytes:
        ...
    
class SaslMechanismScram(SaslMechanism):
    def __init__(self, **config) -> None:
        ...
    
    def auth_bytes(self) -> bytes:
        ...
    
    def receive(self, auth_bytes) -> bool:
        ...
    
    def is_done(self) -> bool:
        ...
    
    def is_authenticated(self) -> bool:
        ...
    
    def auth_details(self) -> LiteralString:
        ...
    


class ScramClient:
    MECHANISMS = ...
    def __init__(self, user, password, mechanism) -> None:
        ...
    
    def first_message(self):
        ...
    
    def process_server_first_message(self, server_first_message) -> None:
        ...
    
    def hmac(self, key, msg) -> bytes:
        ...
    
    def create_salted_password(self, salt, iterations) -> None:
        ...
    
    def final_message(self) -> bytes:
        ...
    
    def process_server_final_message(self, server_final_message) -> None:
        ...
    


