"""
This type stub file was generated by pyright.
"""

import abc
from kafka.vendor.six import add_metaclass

@add_metaclass(abc.ABCMeta)
class AbstractType:
    @abc.abstractmethod
    def encode(cls, value) -> None:
        ...
    
    @abc.abstractmethod
    def decode(cls, data) -> None:
        ...
    
    @classmethod
    def repr(cls, value) -> str:
        ...
    


