"""
This type stub file was generated by pyright.
"""

from kafka.protocol.struct import Struct

class ConsumerProtocolMemberMetadata_v0(Struct):
    SCHEMA = ...


class ConsumerProtocolMemberAssignment_v0(Struct):
    SCHEMA = ...
    def partitions(self) -> list[TopicPartition]:
        ...
    


class ConsumerProtocol_v0:
    PROTOCOL_TYPE = ...
    METADATA = ConsumerProtocolMemberMetadata_v0
    ASSIGNMENT = ConsumerProtocolMemberAssignment_v0


ConsumerProtocol = ...
