"""
This type stub file was generated by pyright.
"""

class Subscription:
    __slots__ = ...
    def __init__(self, metadata, group_instance_id) -> None:
        ...
    
    @property
    def version(self):
        ...
    
    @property
    def user_data(self):
        ...
    
    @property
    def topics(self):
        ...
    
    subscription = ...
    @property
    def group_instance_id(self) -> Any:
        ...
    
    def encode(self):
        ...
    
    def __eq__(self, other) -> bool:
        ...
    


